apiVersion: v1
kind: Service
metadata:
  name: langgraph-service
  namespace: langgraph-safety
spec:
  type: NodePort
  selector:
    app: langgraph-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000
